version: '3.7'
services:
  backend:
    container_name: backend
    image: ${DOCKER_IMAGE_BASE:-transaction-gateway}-api:${DOCKER_TAG:-latest}
    build:
      context: ./
      target: backend
      dockerfile: ./docker/Dockerfile
  cron:
    container_name: cron
    image: ${DOCKER_IMAGE_BASE:-transaction-gateway}-cron:${DOCKER_TAG:-latest}
    build:
      context: ./
      target: cron
      dockerfile: ./docker/Dockerfile
  cli:
    container_name: cli
    image: ${DOCKER_IMAGE_BASE:-transaction-gateway}-cli:${DOCKER_TAG:-latest}
    build:
      context: ./
      target: cli
      dockerfile: ./docker/Dockerfile
