version: '3.7'
services:
  backend:
    ports:
      - 3000:3000
    pull_policy: always
    tty: true
    env_file: .env
    environment:
      - DEV=true
    volumes:
      - ./src:/app/src
      - ./dist:/dist

volumes:
  db:
