version: '3.7'
services:
  backend:
    container_name: backend
    build:
      context: ./
      target: backend
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./.env.api-server
    depends_on:
      - vault

  vault:
    build:
      dockerfile: ./docker/vault.Dockerfile
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN}
    ports:
      - 8200:8200
    container_name: vault
    volumes:
      - ./docker/vault-entrypoint.sh:/docker/vault-entrypoint.sh
      - ./packages/vault/policies/:/policies/
    privileged: true
    entrypoint: ['/bin/bash', 'docker/vault-entrypoint.sh']

  cron:
    container_name: cron
    build:
      context: ./
      target: cron
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./.env.cron
    depends_on:
      - vault
  cli:
    container_name: cli
    build:
      context: ./
      target: cli
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./.env.cli
    depends_on:
      - vault
