version: '3.7'
services:
  backend:
    build:
      context: ./packages/api-server
      target: backend
      dockerfile: ./docker/Dockerfile
    depends_on:
      - backend_db
      - vault

  backend_db:
    image: postgres:15.3-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  vault:
    image: hashicorp/vault:latest
    build:
      dockerfile: ./packages/vault/docker/Dockerfile.vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN}
    ports:
      - 8200:8200
    container_name: vault
    volumes:
      - ./packages/vault/docker/vault-entrypoint.sh:/docker/vault-entrypoint.sh
      - ./packages/vault/cli-policy.vault.hcl:/cli-policy.vault.hcl
      - ./packages/vault/executor-policy.vault.hcl:/executor-policy.vault.hcl
      - ./packages/vault/refiller-policy.vault.hcl:/refiller-policy.vault.hcl
    privileged: true
    entrypoint: ['/bin/bash', 'docker/vault-entrypoint.sh']
