version: '3.7'
services:
  backend:
    build:
      context: ./
      target: backend
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./.env.api-server
    depends_on:
      - vault
      - backend_db

  backend_db:
    image: postgres:15.3-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  vault:
    build:
      dockerfile: ./docker/vault.Dockerfile
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN}
    ports:
      - 8200:8200
    container_name: vault
    volumes:
      - ./docker/vault-entrypoint.sh:/docker/vault-entrypoint.sh
      - ./packages/vault/policies/:/policies/
    privileged: true
    entrypoint: ['/bin/bash', 'docker/vault-entrypoint.sh']
