generic:
  extraVolumes: []
  extraImagePullSecrets:
    - name: ecr-pull-dev-transaction-gateway-api
  usePredefinedAffinity: true

podAffinityPreset: soft

podAntiAffinityPreset: soft

nodeAffinityPreset:
  type: ""
  key: ""
  values: []

releasePrefix: "-"

diagnosticMode:
  enabled: false
  command: ["sleep"]
  args: ["infinity"]

defaultImage: ""
defaultImageTag: "latest"
defaultImagePullPolicy: "IfNotPresent"

services:
  transaction-gateway-api:
    ports:
      - name: http
        protocol: TCP
        port: 80
    extraSelectorLabels:
      app/name: transaction-gateway-api

deployments:
  transaction-gateway-api:
    podLabels:
      app/name: transaction-gateway-api
    replicas: 1
    containers:
      - name: transaction-gateway-api
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 256Mi
#        livenessProbe:
#          httpGet:
#            path: /
#            port: http
#          initialDelaySeconds: 30
#          periodSeconds: 15
#          timeoutSeconds: 10
#          successThreshold: 1
#          failureThreshold: 5
#        readinessProbe:
#          httpGet:
#            path: /
#            port: http
#          initialDelaySeconds: 30
#          periodSeconds: 5
#          timeoutSeconds: 3
#          successThreshold: 1
#          failureThreshold: 3
#        env: {}
        envSecrets:
        - transaction-gateway-api-secret

secrets:
  transaction-gateway-api-secret:
    data:

