common: &common
  name: backend
  serviceSpecificSecret: false
  port:
    source: 3000
    target: 3000
    name: backend

  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi

  livenessProbe:
    failureThreshold: 15
    httpGet:
      path: /v1
      port: 3000
      scheme: HTTP
    initialDelaySeconds: 25
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 3
 
  readinessProbe:
    failureThreshold: 15
    httpGet:
      path: /v1
      port: 3000
      scheme: HTTP
    initialDelaySeconds: 25
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3

dev:
  <<: *common
  kubeNamespace: dev

prod:
  <<: *common
  kubeNamespace: prod
