common: &common
  secretLocation: env-secret

commonDev: &commonDev
  <<: *common
  kubeNamespace: dev

commonProd: &commonProd
  <<: *common
  kubeNamespace: prod

dev:
  - name: transaction-gateway-api
    <<: *commonDev
    secretKey: transactionGatewayAPI
  - name: transaction-gateway-cli
    <<: *commonDev
    secretKey: transactionGatewayCLI
  - name: transaction-gateway-cron
    <<: *commonDev
    secretKey: transactionGatewayCron
  - name: notarization-api
    <<: *commonDev
    secretKey: notarizationAPI

prod:
  - name: transaction-gateway-api
    <<: *commonProd
    secretKey: transactionGatewayAPI
  - name: transaction-gateway-cli
    <<: *commonProd
    secretKey: transactionGatewayCLI
  - name: transaction-gateway-cron
    <<: *commonProd
    secretKey: transactionGatewayCron
  - name: notarization-api
    <<: *commonProd
    secretKey: notarizationAPI
