common: &common
  name: transaction-gateway-cron
  serviceSpecificSecret: false
  resources:
    limits:
      cpu: '500m'
      memory: 1Gi

dev:
  <<: *common
  secretLocation: env-secret
  secretKey: transactionGatewayCron
  imageName: transaction-gateway/cron
  tag: dev
  digest: null
  kubeNamespace: dev

prod:
  <<: *common
  secretLocation: env-secret
  secretKey: transactionGatewayAPI
  kubeNamespace: prod
