name: 'Create Helm Secret Files'
description: 'A reusable action to create Helm secret files'
inputs:
  app:
    description: 'e.g., API, CRON, CLI'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        export APP_UPPER=$(echo "${{ inputs.app }}" | tr '[:lower:]' '[:upper:]')
        SECRET_VAR="VAULTS_SECRETS_$APP_UPPER"
        export SECRET_DATA=$(env | sed -n "s/^${SECRET_VAR}\(.*\)=\(.*\)/\1: \2/p")
        yq e --null-input ".secrets = {\"transaction-gateway-${{ inputs.app }}-secret\": {\"data\": strenv(SECRET_DATA)}}" \
        > "./chart/transaction-gateway-${{ inputs.app }}/transaction-gateway-${{ inputs.app }}-secret.yaml"
      shell: bash