name: DEV Build/Push/Deploy

on:
  workflow_dispatch:

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  helm_deploy_api:
    env:
      APP: api
      DOCKER_IMAGE: ${{needs.docker_build_and_push_api.outputs.docker_image }}
      DOCKER_IMAGE_TAG: ${{needs.docker_build_and_push_api.outputs.docker_tag }}
    needs:
      - docker_build_and_push_api

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/transaction-gateway-${{ env.APP }} * | VAULTS_SECRETS_${{ env.APP }};

      - name: Create Helm secret files
        uses: ./.github/actions/create-helm-secret-files
        with:
          app: ${{ env.APP }}

      - name: Setup Tailscale connection
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: ${{ vars.TS_TAGS }}
          version: ${{ vars.TS_VERSION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ vars.K8S_VERSION }}

      - name: Setup Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ vars.EKS_ENDPOINT }}
          k8s-secret: ${{ secrets.EKS_SA_SECRET }}

      - name: Helm upgrade
        uses: ./.github/actions/helm-upgrade
        with:
          app: ${{ env.APP }}
          docker-image: ${{ env.DOCKER_IMAGE }}
          docker-image-tag: ${{ env.DOCKER_IMAGE_TAG }}

  helm_deploy_cron:
    env:
      APP: cron
      DOCKER_IMAGE: ${{needs.docker_build_and_push_cron.outputs.docker_image }}
      DOCKER_IMAGE_TAG: ${{needs.docker_build_and_push_cron.outputs.docker_tag }}
    needs:
      - docker_build_and_push_cron

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/transaction-gateway-${{ env.APP }} * | VAULTS_SECRETS_${{ env.APP }};

      - name: Create Helm secret files
        uses: ./.github/actions/create-helm-secret-files
        with:
          app: ${{ env.APP }}

      - name: Setup Tailscale connection
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: ${{ vars.TS_TAGS }}
          version: ${{ vars.TS_VERSION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ vars.K8S_VERSION }}

      - name: Setup Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ vars.EKS_ENDPOINT }}
          k8s-secret: ${{ secrets.EKS_SA_SECRET }}

      - name: Helm upgrade
        uses: ./.github/actions/helm-upgrade
        with:
          app: ${{ env.APP }}
          docker-image: ${{ env.DOCKER_IMAGE }}
          docker-image-tag: ${{ env.DOCKER_IMAGE_TAG }}

  helm_deploy_cli:
    env:
      APP: cli
      DOCKER_IMAGE: ${{needs.docker_build_and_push_cli.outputs.docker_image }}
      DOCKER_IMAGE_TAG: ${{needs.docker_build_and_push_cli.outputs.docker_tag }}
    needs:
      - docker_build_and_push_cli

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/transaction-gateway-${{ env.APP }} * | VAULTS_SECRETS_${{ env.APP }};

      - name: Create Helm secret files
        uses: ./.github/actions/create-helm-secret-files
        with:
          app: ${{ env.APP }}

      - name: Setup Tailscale connection
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: ${{ vars.TS_TAGS }}
          version: ${{ vars.TS_VERSION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ vars.K8S_VERSION }}

      - name: Setup Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ vars.EKS_ENDPOINT }}
          k8s-secret: ${{ secrets.EKS_SA_SECRET }}

      - name: Helm upgrade
        uses: ./.github/actions/helm-upgrade
        with:
          app: ${{ env.APP }}
          docker-image: ${{ env.DOCKER_IMAGE }}
          docker-image-tag: ${{ env.DOCKER_IMAGE_TAG }}