name: 'EKS Deploy'

on:
  workflow_call:
    inputs:
      app:
        type: string
        required: true
      docker-image:
        type: string
        required: true
      docker-image-tag:
        type: string
        required: true
      namespace:
        type: string
        required: true

jobs:
  template_job:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch secrets from Vault
      id: vault
      uses: hashicorp/vault-action@v2
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: token
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          kv/data/transaction-gateway-${{ env.APP }} * | VAULTS_SECRETS_${{ env.APP }};

    - name: Create Helm Secret Files
      run: |
        export APP_UPPER=$(echo "${{ inputs.app }}" | tr '[:lower:]' '[:upper:]')
        SECRET_VAR="VAULTS_SECRETS_$APP_UPPER"
        export SECRET_DATA=$(env | sed -n "s/^${SECRET_VAR}\(.*\)=\(.*\)/\1: \2/p")
        yq e --null-input ".secrets = {\"transaction-gateway-${{ inputs.app }}-secret\": {\"data\": strenv(SECRET_DATA)}}" \
        > "./chart/transaction-gateway-${{ inputs.app }}/transaction-gateway-${{ inputs.app }}-secret.yaml"
      shell: bash

    - name: Setup Tailscale connection
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: ${{ vars.TS_TAGS }}
        version: ${{ vars.TS_VERSION }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: ${{ vars.K8S_VERSION }}

    - name: Setup Kubernetes context
      uses: azure/k8s-set-context@v3
      with:
        method: service-account
        k8s-url: ${{ secrets.EKS_ENDPOINT }}
        k8s-secret: ${{ secrets.EKS_SA_SECRET }}

    - name: Helm Upgrade
      run: |
        helm upgrade -i ${{ inputs.app }} /chart/transaction-gateway-${{ inputs.app }} --timeout=15m --wait --history-max=3 \
        --namespace ${{ inputs.namespace }} -f ./chart/transaction-gateway-${{ inputs.app }}transaction-gateway-${{ inputs.app }}-secret.yaml \
        --set defaultImage=${{ inputs.docker-image }} \
        --set defaultImageTag=${{ inputs.docker-image-tag }}
      shell: bash